version: "3.7"
services:
  feecc-ipfs-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8082:8082"
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "~/.cache/pip/:/root/.cache/pip"
    links:
      - ipfsnode
    depends_on:
      ipfsnode:
        condition: service_healthy
    environment:
      MONGODB_URI: ""
      MONGO_DATABASE_NAME: ""
      PRODUCTION_ENVIRONMENT: false  # Leave "no" if you want testing credentials to work
      LOCAL_IPFS_ENABLED: true  # Whether to enable local IPFS node publishing or not.
      PY_IPFS_HTTP_CLIENT_DEFAULT_ADDR: '/dns/ipfsnode/tcp/5001/http'  # Node address, don't change
      PINATA_ENABLED: true  # Whether to upload files to Pinata.cloud or not
      PINATA_API: ''  # Pinata.cloud credentials. Leave empty if you don't need it
      PINATA_SECRET_API: ''  # Pinata.cloud credentials. Leave empty if you don't need it
      AUTHENTICATE: true # Whether check authentication or not

  ipfsnode:
    image: ipfs/go-ipfs:master-latest
    restart: always
    volumes:
      - ~/ipfs/ipfs_staging:/export
      - ~/ipfs/ipfs_data:/data/ipfs
    healthcheck:
      interval: 5s
