version: "3.7"
services:
  feecc-ipfs-gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8082:8082"
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "~/.cache/pip/:/root/.cache/pip"
    links:
      - ipfsnode
    environment:
      MONGODB_URI: ''  # Your MongoDB connection URI ending with /db-name
      PRODUCTION_ENVIRONMENT: no  # Leave "no" if you want testing credentials to work
      LOCAL_IPFS_ENABLED: yes  # Whether to enable local IPFS node publishing or not.
      PINATA_ENABLED: yes  # Whether to upload files to Pinata.cloud or not
      PINATA_API: ''  # Pinata.cloud credentials. Leave empty if you don't need it
      PINATA_SECRET_API: ''  # Pinata.cloud credentials. Leave empty if you don't need it
      ROBONOMICS_ENABLE_DATALOG: no  # Whether to post CIDs to Robonomics network datalog or not
      ROBONOMICS_ACCOUNT_SEED: ''  # Robonomics network account seed
      ROBONOMICS_SUBSTRATE_NODE_URL: ''  # Robonomics node URL in case you want to use non-default node
      PY_IPFS_HTTP_CLIENT_DEFAULT_ADDR: '/dns/ipfsnode/tcp/5001/http'  # Node address, don't change
      AUTH_MODE: "workbench" # Auth mode. Available options are "analytics", "workbench" and "noauth"

  ipfsnode:
    image: ipfs/go-ipfs:master-latest
    restart: always
    volumes:
      - ~/ipfs/ipfs_staging:/export
      - ~/ipfs/ipfs_data:/data/ipfs
